### ISSUE TITLE
Can i use python for solving the DSA Problems?

### ISSUE THREAD

**Issue by biswajitpat** [carpetbhaiya/Hacktoberfest2022v1#3]
Can i use python or c for solving the sorting problems?

**Comment by carpetbhaiya** [comment]
yes you can :)

**Comment by biswajitpat** [comment]
I have already added 2 sorting problems please check them. And if you
assign me some more issues then I can do some more work.

**Comment by carpetbhaiya** [comment]
can you make the readme file more descriptive and intuitive for beginner friendly paticipants

**Comment by biswajitpat** [comment]
Your repo has been excluded from the hactoberfest😣😣
